Repository ecosia/ios-browser, pull requests merged in 2024-04, with the labels that each got.

#651 [MOB-2377] Revert the revert: Add `appleIdfv` to Analytics properties
  Client/Ecosia/Analytics/Analytics+Configuration.swift
Labels: enhancement, Review effort [1-5]: 1

#650 [MOB-2120] Bing Distribution Experiment
  Client.xcodeproj/project.pbxproj
  Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Client/Ecosia/Analytics/Analytics.swift
  Client/Ecosia/Experiments/Unleash/BingDistributionExperiment.swift
  Client/Ecosia/Settings/EcosiaDebugSettings.swift
  Client/Frontend/Browser/BrowserViewController/BrowserViewController+URLBarDelegate.swift
  Client/Frontend/Browser/OpenSearch.swift
  Client/Frontend/Browser/SearchViewController.swift
  Client/Frontend/Settings/AppSettingsTableViewController.swift
  Tests/ClientTests/Ecosia/ExperimentsTests/BingDistributionExperimentTests.swift
Labels: enhancement, tests, Review effort [1-5]: 3

#652 Version bump to 9.4.0
  Client/Configuration/Common.xcconfig
Labels: enhancement, Review effort [1-5]: 1

#653 Align to 9.4.0
  Client.xcodeproj/project.pbxproj
  Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Client/Configuration/Common.xcconfig
  Client/Ecosia/Analytics/Analytics+Configuration.swift
  Client/Ecosia/Analytics/Analytics.swift
  Client/Ecosia/Experiments/Unleash/BingDistributionExperiment.swift
  Client/Ecosia/Extensions/AppSettingsTableViewController+Ecosia.swift
  Client/Ecosia/Settings/EcosiaDebugSettings.swift
  Client/Frontend/Browser/BrowserViewController/Extensions/BrowserViewController+URLBarDelegate.swift
  Client/Frontend/Browser/SearchEngines/OpenSearchEngine.swift
  Client/Frontend/Browser/SearchViewController.swift
  EcosiaTests/BingDistributionExperimentTests.swift
Labels: ff-upgrade-120

#655 Add codium config file to disable automatic PR reviews
  .pr_agent.toml
Labels: Review effort [1-5]: 1, configuration changes
