Repository ecosia/ios-browser, pull requests merged in 2024-03, with the labels that each got.

#624 [MOB-2286] Add Search Engine Shortcut analytics
  Client/Ecosia/Analytics/Analytics.Values.swift
  Client/Ecosia/Analytics/Analytics.swift
  Client/Frontend/Browser/SearchViewController.swift
Labels: enhancement, Review effort [1-5]: 2

#625 [MOB-2283] Add IDFV property to Analytics tracking.
  Client/Ecosia/Analytics/Analytics+Configuration.swift
Labels: enhancement, Review effort [1-5]: 1

#628 Bump version to 9.2.5
  Client/Configuration/Common.xcconfig
Labels: enhancement, Review effort [1-5]: 1

#627 [MOB-2167] Add number of search counts to APNConsent analtytics
  Client/Ecosia/Analytics/Analytics.swift
Labels: enhancement, Review effort [1-5]: 2

#630 Update Release Notes for 9.2.5
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
Labels: documentation, enhancement, Review effort [1-5]: 1

#631 Minor readme formatting and grammar fixes
  README.md
Labels: documentation, Review effort [1-5]: 1

#633 Fix url insecure lock icon appearing on NTP
  Client/Frontend/Toolbar+URLBar/TabLocationView.swift
Labels: Review effort [1-5]: 2, bug_fix

#634 Fix lock icon spacing
  Client.xcodeproj/project.pbxproj
  Client/Ecosia/Extensions/Toolbar+URLBar/ConnectionButton.swift
  Client/Frontend/Toolbar+URLBar/LockButton.swift
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#635 Use custom ecosia disclosure indicator for FF settings
  Client/Ecosia/Settings/EcosiaSettings.swift
  Client/Frontend/Settings/Main/SettingDisclosureUtility.swift
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#636 [MOB-2169 implement apn consent screen reminder
  Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Client/Ecosia/Analytics/Analytics.Values.swift
  Client/Ecosia/EngagementService/EngagementService.swift
  Client/Ecosia/Experiments/Unleash/EngagementServiceExperiment.swift
  Client/Ecosia/Extensions/BrowserViewController+Ecosia.swift
  Client/Ecosia/L10N/String.swift
  Client/Ecosia/UI/APNConsent/APNConsentViewController.swift
  Client/Ecosia/UI/APNConsent/UnleashAPNConsentViewModel.swift
  Client/Frontend/Browser/BrowserViewController.swift
Labels: enhancement, bug_fix, Review effort [1-5]: 4
